### ISSUE TITLE
Comments starting with /*! Not Being Removed 

### ISSUE THREAD

**Issue by Fmakdemir** [jnthnjns/grunt-stripcomments#22]
I realized that in one of js files comment was starting with `/*!` and your grunt plugin wasn't removing it. Checked the source code and found out it was explicitly added. Why was it written like that?
Thanks.

**Comment by Fmakdemir** [comment]
Oh found it at last.. It was a convention to leave out licensing parts :) Sorry for opening an issue

**Comment by jnthnjns** [comment]
@Fmakdemir You are correct, it is always good to leave those contributions and licensing comments. Having said that, I am going to be making this a feature that I will be adding soon.

There is going to be an option `keepSpecialComments` and by default it is going to be set to true which will act as it states and keep them, but this way it will allow you to remove them as well.

I find this useful since I update my banner in my grunt file and I replace my own special comments when I build.

**Comment by Fmakdemir** [comment]
Yes, I think it will be very useful since I came across such a situation. I was using multiple files from same distro so the same license was applying to all files and increasing size unnecessarily.
